// Purpose: Defines the structure of a generated lesson note, rebuilt to
// match the real Ghana Education Service lesson plan book format (Week,
// Subject, Class, Strand, Sub-strand, Indicator, Content standard,
// Performance indicator, Core competencies, Key words, T.L.R(s), Ref,
// and the three teaching phases: Starter, Main, Plenary).
// Folder: lib/ai/lessonSchema.ts

// ----------------------------------------------------------------------------
// Metadata fields: filled in by the teacher (day taught, class size, etc.),
// never generated by AI — these are lesson logistics, not curriculum
// content, so there is nothing for the AI to ground or verify here. They
// default to empty strings and the teacher fills them in the editor,
// exactly like writing them by hand in the paper lesson plan book.
// ----------------------------------------------------------------------------
export interface LessonMetadata {
  week_number: string
  week_ending: string
  class_size: string
  days: string // e.g. "Monday, Thursday, Friday"
  date: string
  period: string
  lesson_number: string
}

export function emptyLessonMetadata(): LessonMetadata {
  return {
    week_number: '',
    week_ending: '',
    class_size: '',
    days: '',
    date: '',
    period: '',
    lesson_number: '',
  }
}

// ----------------------------------------------------------------------------
// AI-generated content: grounded in the real curriculum indicator, same
// technique as before — only the fields below are asked of the AI.
// ----------------------------------------------------------------------------
export interface LessonGeneratedContent {
  core_competencies: string[]
  key_words: string[]
  tlrs: string[]        // Teaching and Learning Resources
  references: string
  phase1_starter: string   // Starter: preparing the brain for learning
  phase2_main: string      // Main: new learning, including assessment
  phase3_plenary: string   // Plenary / Reflections
}

export type LessonNoteContent = LessonMetadata & LessonGeneratedContent

export const LESSON_JSON_SCHEMA_DESCRIPTION = `{
  "core_competencies": ["string", ...],
  "key_words": ["string", ...],
  "tlrs": ["string", ...],
  "references": "string",
  "phase1_starter": "string",
  "phase2_main": "string",
  "phase3_plenary": "string"
}`

// Only checks the AI-generated fields — metadata is always present via
// emptyLessonMetadata() defaults, so there's nothing from the AI to
// validate there.
export function isValidLessonNote(value: unknown): value is LessonGeneratedContent {
  if (typeof value !== 'object' || value === null) return false
  const requiredKeys: (keyof LessonGeneratedContent)[] = [
    'core_competencies', 'key_words', 'tlrs', 'references',
    'phase1_starter', 'phase2_main', 'phase3_plenary',
  ]
  return requiredKeys.every((key) => key in (value as Record<string, unknown>))
}
